Repository inveniosoftware/invenio-app-ils, pull requests merged in 2019-05, with the labels that each got.

#299 item: fix date type in schema
  invenio_app_ils/mappings/v6/items/item-v1.0.0.json
Labels: review

#303 Elastic search delay as constant
  invenio_app_ils/ui/src/invenio_app_ils/common/config.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LocationList/state/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/PatronDetails/components/ItemsSearch/components/ResultsList/ResultsList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/PatronDetails/components/ItemsSearch/state/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/PatronDetails/components/PatronCurrentLoans/state/__tests__/actions.js
Labels: review

#297 delete internal location
  invenio_app_ils/records/api.py
  invenio_app_ils/search/api.py
  invenio_app_ils/ui/src/invenio_app_ils/common/api/locations/internalLocation.js
  invenio_app_ils/ui/src/invenio_app_ils/common/api/locations/location.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LocationList/LocationList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LocationList/components/InternalLocationList/InternalLocationList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LocationList/components/InternalLocationList/index.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LocationList/components/InternalLocationList/state/__tests__/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LocationList/components/InternalLocationList/state/__tests__/reducer.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LocationList/components/InternalLocationList/state/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LocationList/components/InternalLocationList/state/reducer.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LocationList/components/InternalLocationList/state/types.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LocationList/state/__tests__/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LocationList/state/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/components/DeleteRecordModal/DeleteRecordModal.js
  tests/api/test_record_delete.py
  tests/data/internal_locations.json
Labels: review

#308 delete keyword
  invenio_app_ils/config.py
  invenio_app_ils/records/api.py
  invenio_app_ils/search/api.py
  tests/api/test_record_delete.py
Labels: review

#243 api: add electronic items data model
  invenio_app_ils/api.py
  invenio_app_ils/circulation/api.py
  invenio_app_ils/circulation/utils.py
  invenio_app_ils/cli.py
  invenio_app_ils/config.py
  invenio_app_ils/indexer.py
  invenio_app_ils/mappings/v6/documents/document-v1.0.0.json
  invenio_app_ils/mappings/v6/eitems/eitem-v1.0.0.json
  invenio_app_ils/mappings/v6/items/item-v1.0.0.json
  invenio_app_ils/pidstore/fetchers.py
  invenio_app_ils/pidstore/minters.py
  invenio_app_ils/pidstore/pids.py
  invenio_app_ils/pidstore/providers.py
  invenio_app_ils/records/api.py
  invenio_app_ils/records/loaders/__init__.py
  invenio_app_ils/records/loaders/schemas/json/document.py
  invenio_app_ils/records/loaders/schemas/json/item.py
  invenio_app_ils/records/loaders/schemas/json/items.py
  invenio_app_ils/records/resolver/__init__.py
  invenio_app_ils/records/resolver/jsonresolver/__init__.py
  invenio_app_ils/records/resolver/jsonresolver/document_circulation.py
  invenio_app_ils/records/resolver/jsonresolver/document_eitem.py
  invenio_app_ils/records/resolver/jsonresolver/document_keyword.py
  invenio_app_ils/records/resolver/jsonresolver/eitem.py
  invenio_app_ils/records/resolver/jsonresolver/internal_location.py
  invenio_app_ils/records/resolver/jsonresolver/item_document.py
  invenio_app_ils/records/resolver/jsonresolver/item_internal_location.py
  invenio_app_ils/records/resolver/jsonresolver/item_loan.py
  invenio_app_ils/records/resolver/loan.py
  invenio_app_ils/records/resolver/resolver.py
  invenio_app_ils/schemas/documents/document-v1.0.0.json
  invenio_app_ils/schemas/eitems/eitem-v1.0.0.json
  invenio_app_ils/schemas/items/item-v1.0.0.json
  invenio_app_ils/search/api.py
  setup.py
  tests/api/conftest.py
  tests/api/helpers.py
  tests/api/test_apis.py
  tests/api/test_item_permissions_endpoint.py
  tests/api/test_loaders.py
  tests/data/eitems.json
  tests/data/items.json
Labels: review

#315 ui: route urls refactoring
  invenio_app_ils/ui/src/invenio_app_ils/App.js
  invenio_app_ils/ui/src/invenio_app_ils/authentication/components/AuthenticationGuard/__tests__/AuthenticationGuard.js
  invenio_app_ils/ui/src/invenio_app_ils/authentication/components/AuthenticationGuard/__tests__/__snapshots__/AuthenticationGuard.js.snap
  invenio_app_ils/ui/src/invenio_app_ils/authentication/components/UnAuthorized/UnAuthorized.js
  invenio_app_ils/ui/src/invenio_app_ils/common/urls.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentDetails/__tests__/DocumentDetailsContainer.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentDetails/components/DocumentItems/DocumentItems.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentDetails/components/DocumentItems/__tests__/DocumentItems.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentDetails/components/DocumentItems/__tests__/__snapshots__/DocumentItems.js.snap
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentDetails/components/DocumentMetadata/DocumentMetadata.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentDetails/components/DocumentPendingLoans/DocumentPendingLoans.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentDetails/components/DocumentPendingLoans/__tests__/DocumentPendingLoans.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentsSearch/DocumentsSearch.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentsSearch/components/ResultsList/ResultsList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/Home/components/lists/IdleLoansList/IdleLoansList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/Home/components/lists/IdleLoansList/__tests__/IdleLoansList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/Home/components/lists/OverbookedDocumentsList/OverbookedDocumentsList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/Home/components/lists/OverbookedDocumentsList/__tests__/OverbookedDocumentsList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/Home/components/lists/OverdueLoansList/OverdueLoansList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/Home/components/lists/OverdueLoansList/__tests__/OverdueLoansList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/Home/components/lists/RenewedLoansList/RenewedLoansList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/Home/components/lists/RenewedLoansList/__tests__/RenewedLoansList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/Home/components/widgets/DocumentsCard/DocumentsCard.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/Home/components/widgets/DocumentsCard/__tests__/DocumentsCard.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/Home/components/widgets/LoansCard/LoansCard.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/Home/components/widgets/LoansCard/__tests__/LoansCard.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/ItemDetails/__tests__/ItemDetailsContainer.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/ItemDetails/components/ItemMetadata/ItemMetadata.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/ItemDetails/components/ItemMetadata/components/CreateNewLoanModal/CreateNewLoanModal.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/ItemDetails/components/ItemPastLoans/ItemPastLoans.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/ItemDetails/components/ItemPastLoans/__tests__/ItemPastLoans.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/ItemsSearch/ItemsSearch.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/ItemsSearch/components/ResultsList/ResultsList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LoanDetails/__tests__/LoanDetailsContainer.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LoanDetails/components/AvailableItems/AvailableItems.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LoansSearch/LoansSearch.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LocationList/LocationList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LocationList/components/InternalLocationList/InternalLocationList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/PatronDetails/__tests__/PatronDetailsContainer.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/PatronDetails/components/ItemsSearch/ItemsSearch.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/PatronDetails/components/ItemsSearch/__tests__/ItemsSearch.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/PatronDetails/components/PatronCurrentLoans/PatronCurrentLoans.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/PatronDetails/components/PatronCurrentLoans/__tests__/PatronCurrentLoans.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/PatronDetails/components/PatronPendingLoans/PatronPendingLoans.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/PatronDetails/components/PatronPendingLoans/__tests__/PatronPendingLoans.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/PatronsSearch/PatronsSearch.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/components/Header/Header.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/DocumentsSearch/DocumentsSearch.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/components/Header/Header.js
  invenio_app_ils/ui/src/invenio_app_ils/routes/components/BackOffice/BackOffice.js
  invenio_app_ils/ui/src/invenio_app_ils/routes/components/BackOffice/BackOffice.scss
  invenio_app_ils/ui/src/invenio_app_ils/routes/components/BackOffice/index.js
  invenio_app_ils/ui/src/invenio_app_ils/routes/components/FrontSite/FrontSite.js
  invenio_app_ils/ui/src/invenio_app_ils/routes/components/FrontSite/FrontSite.scss
  invenio_app_ils/ui/src/invenio_app_ils/routes/components/FrontSite/index.js
  invenio_app_ils/ui/src/invenio_app_ils/routes/components/index.js
  invenio_app_ils/ui/src/invenio_app_ils/routes/urls.js
Labels: review

#300 delete item
  invenio_app_ils/records/api.py
  invenio_app_ils/records/resolver/loan.py
  invenio_app_ils/ui/package-lock.json
  invenio_app_ils/ui/public/index.html
  invenio_app_ils/ui/src/invenio_app_ils/common/api/items/item.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentDetails/components/DocumentItems/state/__tests__/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/ItemDetails/ItemDetailsContainer.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/ItemDetails/__tests__/ItemDetailsContainer.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/ItemDetails/components/ItemMetadata/ItemMetadata.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/ItemDetails/components/ItemMetadata/index.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/ItemDetails/index.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/ItemDetails/state/__tests__/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/ItemDetails/state/__tests__/reducer.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/ItemDetails/state/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/ItemDetails/state/reducer.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/ItemDetails/state/types.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LoanDetails/components/AvailableItems/AvailableItems.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LoanDetails/components/AvailableItems/state/__tests__/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LoanDetails/components/LoanMetadata/LoanMetadata.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/PatronDetails/components/ItemsSearch/state/__tests__/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/components/buttons/EditButton/EditButton.js
  invenio_app_ils/views.py
Labels: review

#325 loaders: inject pid_field per record class
  invenio_app_ils/config.py
  invenio_app_ils/records/loaders/schemas/json/document.py
  invenio_app_ils/records/loaders/schemas/json/internal_location.py
  invenio_app_ils/records/loaders/schemas/json/items.py
  invenio_app_ils/records/loaders/schemas/json/keyword.py
  invenio_app_ils/records/loaders/schemas/json/location.py
  setup.py
Labels: review

#293 home-page: adding most recent/loaned document views
  invenio_app_ils/circulation/views.py
  invenio_app_ils/ui/src/invenio_app_ils/__tests__/App.js
  invenio_app_ils/ui/src/invenio_app_ils/common/api/documents/document.js
  invenio_app_ils/ui/src/invenio_app_ils/common/components/SearchBar/SearchBar.js
  invenio_app_ils/ui/src/invenio_app_ils/common/components/SearchBar/__tests__/SearchBar.js
  invenio_app_ils/ui/src/invenio_app_ils/common/components/SearchBar/__tests__/__snapshots__/SearchBar.js.snap
  invenio_app_ils/ui/src/invenio_app_ils/history.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/Home/Home.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/Home/Home.scss
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/Home/components/DocumentCard/DocumentCard.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/Home/components/DocumentCard/index.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/Home/components/MostLoanedDocuments/MostLoanedDocuments.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/Home/components/MostLoanedDocuments/index.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/Home/components/MostLoanedDocuments/state/__tests__/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/Home/components/MostLoanedDocuments/state/__tests__/reducer.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/Home/components/MostLoanedDocuments/state/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/Home/components/MostLoanedDocuments/state/reducer.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/Home/components/MostLoanedDocuments/state/types.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/Home/components/MostRecentDocuments/MostRecentDocuments.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/Home/components/MostRecentDocuments/index.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/Home/components/MostRecentDocuments/state/__tests__/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/Home/components/MostRecentDocuments/state/__tests__/reducer.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/Home/components/MostRecentDocuments/state/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/Home/components/MostRecentDocuments/state/reducer.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/Home/components/MostRecentDocuments/state/types.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/Home/components/index.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/Home/config.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/Home/reducer.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/components/Header/Header.js
  invenio_app_ils/ui/src/invenio_app_ils/routes/urls.js
  invenio_app_ils/ui/src/invenio_app_ils/store.js
Labels: review

#330 Redirect to correct url after item delete
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/ItemDetails/state/actions.js
Labels: bug, review

#329 home-page: fix search bar
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/Home/Home.js
Labels: review

#333 Required document_pid on document create
  invenio_app_ils/records/loaders/schemas/json/document.py
Labels: approved

#332 UI: decrease disappearing success notification time
  invenio_app_ils/ui/src/invenio_app_ils/common/components/Notifications/messages.js
  invenio_app_ils/ui/src/invenio_app_ils/common/config.js
Labels: review

#335 Delete document
  invenio_app_ils/records/api.py
  invenio_app_ils/ui/src/invenio_app_ils/common/api/documents/document.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentDetails/DocumentDetailsContainer.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentDetails/__tests__/DocumentDetailsContainer.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentDetails/components/DocumentMetadata/DocumentMetadata.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentDetails/components/DocumentMetadata/index.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentDetails/index.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentDetails/state/__tests__/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentDetails/state/__tests__/reducer.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentDetails/state/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentDetails/state/reducer.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentDetails/state/types.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/ItemDetails/components/ItemMetadata/ItemMetadata.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/ItemDetails/state/__tests__/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/ItemDetails/state/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LocationList/LocationList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LocationList/components/InternalLocationList/InternalLocationList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LocationList/components/InternalLocationList/state/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LocationList/state/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/components/DeleteRecordModal/DeleteRecordModal.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/components/DeleteRecordModal/index.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/components/DeleteRecordModal/state/__tests__/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/components/DeleteRecordModal/state/__tests__/reducer.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/components/DeleteRecordModal/state/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/components/DeleteRecordModal/state/reducer.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/components/buttons/EditButton/EditButton.js
Labels: review
