Repository inveniosoftware/invenio-app-ils, pull requests merged in 2019-04, with the labels that each got.

#212 frontsite: book details page initial version
  invenio_app_ils/circulation/search.py
  invenio_app_ils/cli.py
  invenio_app_ils/records/jsonresolver/document.py
  invenio_app_ils/schemas/documents/document-v1.0.0.json
  invenio_app_ils/ui/src/invenio_app_ils/App.js
  invenio_app_ils/ui/src/invenio_app_ils/common/urls.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentsSearch/__tests__/ResultsList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentsSearch/__tests__/__snapshots__/ResultsList.js.snap
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LoanDetails/components/LoanMetadata/LoanMetadata.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/PatronCurrentLoans/PatronCurrentLoans.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/PatronCurrentLoans/__tests__/PatronCurrentLoans.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/PatronCurrentLoans/__tests__/__snapshots__/PatronCurrentLoans.js.snap
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/UserMetadata/UserMetadata.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/BookDetails.scss
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/BookDetailsContainer.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/__tests__/BookDetailsContainer.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/__tests__/__snapshots__/BookDetailsContainer.js.snap
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/components/BookDetails/BookDetails.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/components/BookDetails/index.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/components/BookMetadata/BookMetadata.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/components/BookMetadata/components/RequestNewLoanForm/RequestNewLoanForm.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/components/BookMetadata/components/RequestNewLoanForm/index.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/components/BookMetadata/components/RequestNewLoanForm/state/__tests__/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/components/BookMetadata/components/RequestNewLoanForm/state/__tests__/reducer.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/components/BookMetadata/components/RequestNewLoanForm/state/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/components/BookMetadata/components/RequestNewLoanForm/state/reducer.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/components/BookMetadata/components/RequestNewLoanForm/state/types.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/components/BookMetadata/index.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/components/BookTab/BookTab.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/components/BookTab/components/BookAccordion/BookAccordion.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/components/BookTab/components/BookAccordion/index.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/components/BookTab/components/BookTabMenu/BookTabMenu.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/components/BookTab/components/BookTabMenu/index.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/components/BookTab/index.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/components/index.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/index.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/reducer.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/state/__tests__/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/state/__tests__/reducer.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/state/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/state/reducer.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/state/types.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/components/Header/Header.scss
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/index.js
  invenio_app_ils/ui/src/invenio_app_ils/routes/FrontSite.js
  invenio_app_ils/ui/src/invenio_app_ils/store.js
  setup.py
  tests/data/documents.json
Labels: review

#214 records: add keyword record
  invenio_app_ils/cli.py
  invenio_app_ils/config.py
  invenio_app_ils/errors.py
  invenio_app_ils/mappings/v6/documents/document-v1.0.0.json
  invenio_app_ils/mappings/v6/keywords/keyword-v1.0.0.json
  invenio_app_ils/pidstore/fetchers.py
  invenio_app_ils/pidstore/minters.py
  invenio_app_ils/pidstore/pids.py
  invenio_app_ils/pidstore/providers.py
  invenio_app_ils/records/api.py
  invenio_app_ils/records/jsonresolver/internal_location.py
  invenio_app_ils/records/jsonresolver/item_internal_location.py
  invenio_app_ils/records/jsonresolver/item_loan.py
  invenio_app_ils/records/jsonresolver/keyword.py
  invenio_app_ils/records/jsonresolver/loan.py
  invenio_app_ils/records/loaders/__init__.py
  invenio_app_ils/records/loaders/schemas/json/document.py
  invenio_app_ils/records/loaders/schemas/json/keyword.py
  invenio_app_ils/schemas/documents/document-v1.0.0.json
  invenio_app_ils/schemas/keywords/keyword-v1.0.0.json
  invenio_app_ils/ui/public/index.html
  invenio_app_ils/ui/src/invenio_app_ils/common/__mocks__/config.js
  invenio_app_ils/ui/src/invenio_app_ils/common/api/documents/document.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentDetails/components/DocumentMetadata/DocumentMetadata.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentsSearch/DocumentsSearch.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentsSearch/config.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/components/BookMetadata/BookMetadata.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/components/BookTab/BookTab.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/components/BookTab/components/BookAccordion/BookAccordion.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/components/BookTab/components/BookTabMenu/BookTabMenu.js
  setup.py
  tests/api/conftest.py
  tests/api/test_errors.py
  tests/api/test_keywords.py
  tests/data/keywords.json
Labels: review

#230 celery: logging for indexers
  invenio_app_ils/indexer.py
Labels: review

#204 Query builder helper
  invenio_app_ils/cli.py
  invenio_app_ils/config.py
  invenio_app_ils/mappings/v6/documents/document-v1.0.0.json
  invenio_app_ils/schemas/documents/document-v1.0.0.json
  invenio_app_ils/ui/public/index.html
  invenio_app_ils/ui/src/invenio_app_ils/common/components/SearchBar/SearchBar.js
  invenio_app_ils/ui/src/invenio_app_ils/common/components/SearchBar/__tests__/SearchBar.js
  invenio_app_ils/ui/src/invenio_app_ils/common/components/SearchBar/__tests__/__snapshots__/SearchBar.js.snap
  invenio_app_ils/ui/src/invenio_app_ils/common/components/SearchBar/components/QueryBuildHelper/QueryBuildHelper.js
  invenio_app_ils/ui/src/invenio_app_ils/common/components/SearchBar/components/QueryBuildHelper/index.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentsSearch/DocumentsSearch.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentsSearch/__tests__/__snapshots__/ResultsList.js.snap
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentsSearch/components/ResultsList/ResultsList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentsSearch/config.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/ItemsSearch.js
  invenio_app_ils/views.py
Labels: review

#240 Checkout loader fix
  invenio_app_ils/ui/src/invenio_app_ils/common/api/documents/document.js
  invenio_app_ils/ui/src/invenio_app_ils/common/api/items/item.js
  invenio_app_ils/ui/src/invenio_app_ils/common/api/loans/loan.js
  invenio_app_ils/ui/src/invenio_app_ils/common/components/ResultsTable/formatters.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/ItemsSearch/__tests__/__snapshots__/ResultsList.js.snap
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/ItemsSearch/components/ResultsList/ResultsList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/ItemsSearch.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/__tests__/ItemsSearch.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/__tests__/__snapshots__/ItemsSearch.js.snap
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/index.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/state/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/PatronCurrentLoans/state/__tests__/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/PatronCurrentLoans/state/actions.js
Labels: review

#247 ui: remove status code from error notification
  invenio_app_ils/ui/src/invenio_app_ils/common/components/Notifications/Notifications.scss
  invenio_app_ils/ui/src/invenio_app_ils/common/components/Notifications/messages.js
  invenio_app_ils/ui/src/invenio_app_ils/common/components/Notifications/state/actions.js
Labels: review

#248 backoffice-ui: add ResultsTable name
  invenio_app_ils/ui/src/invenio_app_ils/common/components/ResultsTable/ResultsTable.js
  invenio_app_ils/ui/src/invenio_app_ils/common/components/ResultsTable/__tests__/__snapshots__/ResultsTable.js.snap
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentDetails/components/DocumentItems/DocumentItems.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentDetails/components/DocumentItems/__tests__/__snapshots__/DocumentItems.js.snap
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentDetails/components/DocumentPendingLoans/DocumentPendingLoans.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentDetails/components/DocumentPendingLoans/__tests__/__snapshots__/DocumentPendingLoans.js.snap
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentsSearch/DocumentsSearch.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentsSearch/__tests__/__snapshots__/ResultsList.js.snap
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentsSearch/components/ResultsList/ResultsList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/Home/components/lists/IdleLoansList/IdleLoansList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/Home/components/lists/IdleLoansList/__tests__/__snapshots__/IdleLoansList.js.snap
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/Home/components/lists/OverbookedDocumentsList/OverbookedDocumentsList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/Home/components/lists/OverbookedDocumentsList/__tests__/__snapshots__/OverbookedDocumentsList.js.snap
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/Home/components/lists/OverdueLoansList/OverdueLoansList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/Home/components/lists/OverdueLoansList/__tests__/__snapshots__/OverdueLoansList.js.snap
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/Home/components/lists/RenewedLoansList/RenewedLoansList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/Home/components/lists/RenewedLoansList/__tests__/__snapshots__/RenewedLoansList.js.snap
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/ItemDetails/components/ItemPastLoans/ItemPastLoans.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/ItemDetails/components/ItemPastLoans/__tests__/__snapshots__/ItemPastLoans.js.snap
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/ItemsSearch/__tests__/__snapshots__/ResultsList.js.snap
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/ItemsSearch/components/ResultsList/ResultsList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LoansSearch/LoansSearch.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LoansSearch/__tests__/__snapshots__/ResultsList.js.snap
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LoansSearch/components/ResultsList/ResultsList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LocationList/LocationList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LocationList/components/InternalLocationList/InternalLocationList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/__tests__/__snapshots__/ItemsSearch.js.snap
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/components/ResultsList/ResultsList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/PatronCurrentLoans/PatronCurrentLoans.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/PatronCurrentLoans/__tests__/__snapshots__/PatronCurrentLoans.js.snap
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/PatronPendingLoans/PatronPendingLoans.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/PatronPendingLoans/__tests__/__snapshots__/PatronPendingLoans.js.snap
Labels: review

#249 backoffice-ui: fix empty results barcode search
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/ItemsSearch.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/ItemsSearch.scss
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/__tests__/__snapshots__/ItemsSearch.js.snap
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/components/ResultsList/ResultsList.js
Labels: review

#217 Backoffice: force-checkout loans
  invenio_app_ils/circulation/api.py
  invenio_app_ils/circulation/utils.py
  invenio_app_ils/circulation/views.py
  invenio_app_ils/ui/src/invenio_app_ils/common/api/loans/loan.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentsSearch/components/ResultsList/ResultsList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/LoansSearch/components/ResultsList/ResultsList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsCheckout/index.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsCheckout/state/__tests__/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsCheckout/state/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/ItemsSearch.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/__tests__/ItemsSearch.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/__tests__/__snapshots__/ItemsSearch.js.snap
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/components/ResultsList/ResultsList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/ItemsSearch/index.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/UserDetails/components/PatronCurrentLoans/PatronCurrentLoans.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/BookDetails/BookDetails.scss
  tests/api/test_item_loan_create.py
Labels: review

#254 backoffice ui: add available items facet
  invenio_app_ils/config.py
  invenio_app_ils/ui/public/index.html
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentsSearch/config.js
Labels: review

#236 Sentry integration
  invenio_app_ils/circulation/utils.py
  invenio_app_ils/ext.py
  setup.py
Labels: in progress, infra

#257 circulation: fix issue with anonymous search
  invenio_app_ils/circulation/search.py
  invenio_app_ils/errors.py
  tests/api/test_errors.py
  tests/api/test_loan_list_permissions.py
Labels: review

#272 global: update `invenio_app` version
  setup.py
Labels: review

#284 backoffice: available items facet with ranges
  invenio_app_ils/config.py
  invenio_app_ils/facets.py
  invenio_app_ils/ui/public/index.html
  tests/test_facets.py
Labels: review

#280 backoffice ui: fix errors when pasting barcode
  invenio_app_ils/ui/src/invenio_app_ils/common/api/urls.js
  invenio_app_ils/ui/src/invenio_app_ils/common/components/Error/Error.js
  invenio_app_ils/ui/src/invenio_app_ils/common/components/Notifications/state/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/PatronDetails/components/ItemsCheckout/state/__tests__/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/PatronDetails/components/ItemsCheckout/state/actions.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/PatronDetails/components/ItemsSearch/ItemsSearch.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/PatronDetails/components/ItemsSearch/__tests__/__snapshots__/ItemsSearch.js.snap
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/PatronDetails/components/ItemsSearch/components/ResultsList/ResultsList.js
  invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/PatronDetails/components/ItemsSearch/index.js
Labels: review

#294 patrons: prefix index name
  invenio_app_ils/indexer.py
Labels: approved
